service: tensorflow-lambdaa-regression

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python2.7
  memorySize: 1536
  timeout: 300
  stage: dev
  region: us-west-2

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /predict
          method: get
